#!/bin/bash

FILE=$(find . -name "makelist.txt")

find . -name "*.mak" | xargs rm -f

for list in $FILE; do
	_dir=`dirname $list`
	_mod=`basename $_dir`
	_makfile="$_dir/`basename $_dir`.mak"

	echo "#############################################################################"	 > $_makfile
	echo "#"																				>> $_makfile
	echo "#   LGE. ROBOT RESEARCH LABORATORY"												>> $_makfile
	echo "#   COPYRIGHT(c) LGE CO.,LTD. 2017. SEOUL, KOREA."								>> $_makfile
	echo "#   All rights are reserved."														>> $_makfile
	echo "#   Do not edit this file! (Automatically created)"								>> $_makfile
	echo "#"																				>> $_makfile		
	echo "#   File Name  : ${_mod}.mak"														>> $_makfile
	echo "#"																				>> $_makfile
	echo "#############################################################################"	>> $_makfile
	cat $list | sed 's/[\t ]*//g' | sed -n '/^srcs/p' | sed "s|srcs|${_mod}_srcs|g"			>> $_makfile
done
